StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5E607228FB8D35BF}" {
   Id "R3D-EditableEntity_Mk82_Name"
   Target_en_us "Mk82 500lb Bomb"
   Comment "Enity placed via the content Browser"
   MaxLength 28
   Modified 1583379029
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
   Labels {
    300
   }
   SourceFile "{944A2BBB73EDBD63}PrefabsEditable/Auto/Weapons/HeavyWeapons/Mk82/E_Mk82.et"
  }
 }
}