modded enum SCR_DebugMenuID
{
	DEBUGUI_R3DCORE_MENU,
	
	// Airplanes
	DEBUGUI_R3DCORE_AIRPLANES_MENU,
	DEBUGUI_R3DCORE_AIRPLANES_SHOWATMOSPHEREDEBUG,
	DEBUGUI_R3DCORE_AIRPLANES_SHOWPANELSDEBUG,
	DEBUGUI_R3DCORE_AIRPLANES_SHOWNORMALSDEBUG,
	DEBUGUI_R3DCORE_AIRPLANES_SHOWPLANEDEBUG,
	DEBUGUI_R3DCORE_AIRPLANES_SHOWWIND,
	DEBUGUI_R3DCORE_AIRPLANES_SHOWINPUT,
	DEBUGUI_R3DCORE_AIRPLANES_SHOWENGINEDEBUG
}

modded class ArmaReforgerScripted
{
	static string DEBUGUI_R3DCORE_MENU = "Project Redline";
	static string DEBUGUI_R3DCORE_AIRPLANES_MENU = "[R3D] Airplanes";
	
	void ArmaReforgerScripted()
	{
		// Primary Menu
		DiagMenu.RegisterMenu(SCR_DebugMenuID.DEBUGUI_R3DCORE_MENU, DEBUGUI_R3DCORE_MENU, "");

		// Airplane Menu		
		DiagMenu.RegisterMenu(SCR_DebugMenuID.DEBUGUI_R3DCORE_AIRPLANES_MENU, DEBUGUI_R3DCORE_AIRPLANES_MENU, DEBUGUI_R3DCORE_MENU);	
		DiagMenu.RegisterBool(SCR_DebugMenuID.DEBUGUI_R3DCORE_AIRPLANES_SHOWATMOSPHEREDEBUG, "", "Atmosphere Properties", DEBUGUI_R3DCORE_AIRPLANES_MENU);
		DiagMenu.RegisterBool(SCR_DebugMenuID.DEBUGUI_R3DCORE_AIRPLANES_SHOWPLANEDEBUG, "", "Plane Debug", DEBUGUI_R3DCORE_AIRPLANES_MENU);
		DiagMenu.RegisterBool(SCR_DebugMenuID.DEBUGUI_R3DCORE_AIRPLANES_SHOWWIND, "", "Show Wind Vector", DEBUGUI_R3DCORE_AIRPLANES_MENU);
		DiagMenu.RegisterBool(SCR_DebugMenuID.DEBUGUI_R3DCORE_AIRPLANES_SHOWPANELSDEBUG, "", "Show Panels", DEBUGUI_R3DCORE_AIRPLANES_MENU);
		DiagMenu.RegisterBool(SCR_DebugMenuID.DEBUGUI_R3DCORE_AIRPLANES_SHOWNORMALSDEBUG, "", "Show Normals", DEBUGUI_R3DCORE_AIRPLANES_MENU);
		DiagMenu.RegisterBool(SCR_DebugMenuID.DEBUGUI_R3DCORE_AIRPLANES_SHOWINPUT, "", "Show Input", DEBUGUI_R3DCORE_AIRPLANES_MENU);
		DiagMenu.RegisterBool(SCR_DebugMenuID.DEBUGUI_R3DCORE_AIRPLANES_SHOWENGINEDEBUG, "", "Show Engine Debug", DEBUGUI_R3DCORE_AIRPLANES_MENU);
	}
	
	override bool OnGameStart()
	{
		bool success = super.OnGameStart();
		
		return true;
	}
}